version: "3"
services:
  webapp:
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - redis
      - db
  db:
    image: postgres:15
    restart: always
    container_name: metaversitas-db-postgres
    volumes:
      - metaversitas-volume:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d metaversitas -u admin"]
      interval: 1s
      timeout: 5s
      retries: 10
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    container_name: metaversitas-redis
    volumes:
      - metaversitas-redis-volume:/data/
volumes:
  metaversitas-volume:
    driver: local
  metaversitas-redis-volume:
    driver: local
