'use client'
import React, { PropsWithChildren } from 'react'
import '@/app/globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import Providers from '@/app/providers'
import withTheme from '@/theme/withTheme'

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ['500', '600', '700', '800'],
  subsets: ['latin']
})

// export const metadata = {
//   title: 'Metaversitas',
//   description: 'Generated by create next app'
// }

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body className={plusJakartaSans.className}>
      <Providers>{children}</Providers>
    </body>
  </html>
)

export default withTheme(RootLayout)
